const menu = [
  {
    id: 1,
    title: 'fluffy stack delight',
    category: 'breakfast',
    price: 15.99,
    img: '/images/item-1.jpeg',
    desc: `In the heart of a bustling city, where dreams intertwine with the rhythm of life, there exists a hidden sanctuary known only to a select few. This sanctuary, nestled amidst the chaos of urban existence, is a place of refuge and contemplation. Here, time seems to slow down, and the worries of the world melt away. `,
  },
  {
    id: 2,
    title: 'ultimate patty paradise',
    category: 'lunch',
    price: 13.99,
    img: '/images/item-2.jpeg',
    desc: `Deep within the heart of the forest, where the trees stand tall and proud, there lies a hidden glade untouched by the hands of man. Here, the air is cool and crisp, filled with the scent of pine and earth. Sunlight filters through the canopy above, casting a warm glow on the moss-covered ground below. Butterflies flit through the air, their delicate wings shimmering in the sunlight.`,
  },
  {
    id: 3,
    title: 'creamy dream swirl',
    category: 'shakes',
    price: 6.99,
    img: '/images/item-3.jpeg',
    desc: `High atop a windswept cliff, overlooking the vast expanse of the ocean, there stands a solitary lighthouse, its beacon cutting through the darkness like a guiding star. This beacon of hope stands as a sentinel against the raging sea, a symbol of strength and resilience in the face of adversity.`,
  },
  {
    id: 4,
    title: 'morning glory medley',
    category: 'breakfast',
    price: 20.99,
    img: '/images/item-4.jpeg',
    desc: `In the heart of the desert, where the sun beats down relentlessly and the sand stretches out as far as the eye can see, there exists an oasis of life amidst the barren wasteland. Here, amidst the shimmering heat, stands a cluster of palm trees, their fronds swaying gently in the breeze.  `,
  },
  {
    id: 5,
    title: 'yolk-tastic combo',
    category: 'lunch',
    price: 22.99,
    img: '/images/item-5.jpeg',
    desc: `In the heart of the mountains, where the air is thin and the snow-capped peaks reach towards the sky, there exists a hidden valley, untouched by the hand of man. Here, amidst the rugged beauty of the wilderness, life flourishes in abundance. `,
  },
  {
    id: 6,
    title: 'oreo heaven chiller',
    category: 'shakes',
    price: 18.99,
    img: '/images/item-6.jpeg',
    desc: `Deep beneath the surface of the earth, where darkness reigns supreme and the air is heavy with the scent of damp earth, there lies a hidden realm, untouched by the light of day. This subterranean world is a labyrinth of twisting tunnels and caverns, its depths home to strange and wondrous creatures.`,
  },
  {
    id: 7,
    title: 'protein power platter',
    category: 'breakfast',
    price: 8.99,
    img: '/images/item-7.jpeg',
    desc: `In the heart of the jungle, where the air is thick with humidity and the canopy above blocks out the sun, there exists a hidden temple, lost to the passage of time. This ancient temple, built by a long-forgotten civilization, is a testament to the ingenuity and skill of its creators.  `,
  },
  {
    id: 8,
    title: 'sunny side feast',
    category: 'lunch',
    price: 12.99,
    img: '/images/item-8.jpeg',
    desc: `On the edge of a windswept moor, where the heather blooms in shades of purple and gold, there lies a hidden village, its thatched cottages nestled amidst the rolling hills. This idyllic hamlet, far from the noise and bustle of the city, is a place of peace and tranquility.`,
  },
  {
    id: 9,
    title: 'frosty bliss shake',
    category: 'shakes',
    price: 16.99,
    img: '/images/item-9.jpeg',
    desc: `Smoke curls from the chimneys of the cottages, carrying with it the scent of woodsmoke and baking bread. Sheep graze in the fields, their woolly coats a patchwork of white and black.`,
  },
];
export default menu;
